services:
  to_to_list:
    extends:
      file: docker-compose.common.yml
      service: to_to_list
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=DEVELOP
      - DEBUG=True

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

networks:
  to_to_network:

volumes:
  to_to_volume:
