"""Include time_calc Column to ImageHistory

Revision ID: 72397ba0d0ce
Revises: 0a5d2a24fee3
Create Date: 2024-08-22 19:17:26.892922

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72397ba0d0ce'
down_revision: Union[str, None] = '0a5d2a24fee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_history', sa.Column('time_calc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_history', 'time_calc')
    # ### end Alembic commands ###
